package icu4cj.message2


public class FormattedMessage <: FormattedValue {
    
    public init() {
        throw Exception("Not yet implemented.")
    }

    
    public override func length(): Int32 {
        throw Exception("Not yet implemented.")
    }

    
    public override func charAt(index: Int32): Char {
        throw Exception("Not yet implemented.")
    }

    
    public override func subSequence(start: Int32, end: Int32): String {
        throw Exception("Not yet implemented.")
    }

    
    public override func appendTo<A>(appendable: A): A {
        throw Exception("Not yet implemented.")
    }

    
    public override func nextPosition(cfpos: ConstrainedFieldPosition): Bool {
        throw Exception("Not yet implemented.")
    }

    
    public override func toCharacterIterator(): AttributedCharacterIterator {
        throw Exception("Not yet implemented.")
    }
}
