package icu4cj.impl.duration

public interface TimeUnitConstants {
    public static let YEAR = TimeUnit.YEAR

    public static let MONTH = TimeUnit.MONTH

    public static let WEEK = TimeUnit.WEEK

    public static let DAY = TimeUnit.DAY

    public static let HOUR = TimeUnit.HOUR

    public static let MINUTE = TimeUnit.MINUTE

    public static let SECOND = TimeUnit.SECOND

    public static let MILLISECOND = TimeUnit.MILLISECOND
}